spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    view:
      prefix: templates
      suffix: .html
    static-path-pattern: /static/**
  h2:
    console:
      enabled: true

  datasource:
    initialization-mode: embedded

    platform: h2
    url: jdbc:h2:tcp://localhost:8082,/mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true

server:
  port: 8001
  servlet:
    context-path: /

# TODO springboot 로깅 방법 설명 1. yaml, 2. logback.xml
logging:
  level:
    root: info


decorator:
  datasource:
    enabled: true
